export type Bot = {
  algoId: string;
  algoClOrdId: string;
  algoOrdType: string;
  state: string;
  maxPx: string;
  minPx: string;
  gridNum: string;
  runType: string;
  arbitrageNum: string;
  totalPnl: string;
  pnlRatio: string;
  investment: string;
  gridProfit: string;
  floatProfit: string;
  instFamily: string;
  limitPrice: string;
  instId: string;
  liqPx: string;
};
